name: HighriseSF

author: cworldstar

description: A generic Slimefun4-Addon

main: me.cworldstar.highriseSF.HighriseSF

website: https://github.com/Sniperkaos/HighriseSF

version: ${project.version}

api-version: 1.20

depend:
- Slimefun

commands:
  itemmeta:
    description: "This is a command"
    usage: "/command <arg>"
    aliases: [im, imeta, itemmeta]
    permission: permission.itemmeta
    permission-message: "You do not have permission to use this command"